### ISSUE TITLE
add option for comment style

### ISSUE THREAD

**Issue by changethe** [edheltzel/nunjucks-for-visual-studio-code#9]
as mentioned in #1, the fact that the extension overrides the default comment style in all html files can be very frustrating.

I would suggest adding a configuration option to revert the comment style to default html comments.

it is probably even a good idea to leave the html style as default and make the nunjucks-style optional.

**Comment by edheltzel** [comment]
As of right now, the [suggested keybinding](https://github.com/edheltzel/nunjucks-for-visual-studio-code/issues/1#issuecomment-1107923527) is the only solution. 

I do have plans on a complete rewrite of the extension to leverage VSCode's Embedded language server to make features and extend the grammar easier, but time is not on my side due to other obligations.

I'd be happy to review and accept pull requests if you have an ideal temporary solution. I'd also be willing to move this issue to a discussion to talk about features to include in the rewrite: such as Nunjucks formatting, snippets for extending native Nunjuck filters, adding a configuration file for project detection/overrides, etc.

**Comment by edheltzel** [comment]
That's a good edition.

If you want to update the read with that info, you can create a PR.
